version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: unless-stopped
    env_file:
    - ./backend/.env
  backend-app:
    build: ./backend  
    image: class-backend:latest
    container_name: class-backend
    ports:
      - '8000:8000'
    env_file:
    - ./backend/.env
    depends_on:
      - postgres 
    restart: on-failure
    links:
        - "postgres:database"
